### ISSUE TITLE
Button to refresh available repositories

### ISSUE THREAD

**Issue by frewsxcv** [AelitaBot/aelita#103]
I created a new repository but it doesn't appear in the list of repositories I can add to aelita

**Comment by notriddle** [comment]
If it's a private repo, then that's a feature, not a bug...

**Comment by frewsxcv** [comment]
This is a separate issue than the one I mentioned in Gitter. Trying to add aelita to https://github.com/rust-syndication/rss

**Comment by notriddle** [comment]
Are you an admin in that org?

**Comment by frewsxcv** [comment]
![screen shot 2016-09-02 at 5 25 38 pm](https://cloud.githubusercontent.com/assets/416575/18218657/49ddce38-7132-11e6-98a5-d6379994915c.png)

**Comment by notriddle** [comment]
I've found the problem. The organization needs to grant the Aelita oAuth app access to the organization for that to work.

**Comment by notriddle** [comment]
It's in the organization's Settings area under "Third-party access".

**Comment by frewsxcv** [comment]
![screen shot 2016-11-08 at 1 09 36 pm](https://cloud.githubusercontent.com/assets/416575/20111006/a2620522-a5b4-11e6-9dc4-ee9f2ad027a6.png)

**Comment by notriddle** [comment]
Yeah, you need to either 

* Remove restrictions
* go into your User Settings, then Authorized Applications, then Aelita, then you can grant it Organization Access to rust-syndication

**Comment by notriddle** [comment]
@frewsxcv Did it work?

**Comment by frewsxcv** [comment]
Haven't had time to test it yet, sorry. I'll let you know once I do

**Comment by frewsxcv** [comment]
Yep, that fixed it. Thanks!
