### ISSUE TITLE
Race condition when c-i/a is set as a required status check

### ISSUE THREAD

**Issue by notriddle** [AelitaBot/aelita#110]
Seen in nox/mitochondria#11

# Internal log

```
DEBUG:aelita::vcs::github: Set master SHA: /repos/nox/mitochondria/git/refs/heads/master
WARN:aelita::vcs::github: Failed to move to master: HttpStatus(UnprocessableEntity)
```

# Steps to reproduce

1. Set up aelitabot.xyz on a repo, but do not add @aelita-mergebot as an administrator.
2. Set continuous-integration/aelita as a required status check.
3. Watch the merges randomly fail with ":scream: Internal error while fast-forward master"

# Cause

Status submissions and the actual fast-forwards are done concurrently, so if GitHub rejects the fast forward based on whether or not the status submission has gone through, it causes a race condition.

**Comment by notriddle** [comment]
CC @nox

**Comment by notriddle** [comment]
@nox

Just as a quick check, do you have it set to require continuous-integration/aelita as a check?

**Comment by nox** [comment]
Yes. Should I unset that?

**Comment by notriddle** [comment]
Unfortunately, that doesn't work right unless @aelita-mergebot is also a administrator on the repo, because it submits its check results and fast-forwards master at the same time. If GitHub rejects the merge whenever the results aren't in yet, it creates a race condition.

**Comment by nox** [comment]
I see, I will just unset it then.
