### ISSUE TITLE
Fix license headers

### ISSUE THREAD

**Issue by aneeshusa** [AelitaBot/aelita#26]
Excited to see this project - I'm hoping that this will become a worthy successor to Homu and help decrease infra-related outages and annoyances for Servo. I'd like to get this cleared up before I start to contribute though.

I don't think the current license headers are clear enough about the licensing terms. IANAL, but IMO it would be better to have a copy of the the actual licenses in this repo and update the license headers to the full boilerplate that Rust uses. It would also be nice to mention the license in the README. This makes it 1) easier to find the license for end users 2) prevents problems of ambiguity about which Rust is being referenced 3) gives a stable license even if Rust decides to change its license someday.

Also, as an end-user application and not a library, I personally would appreciate using a copyleft license such as MPL 2.0 or a GPL 3.0(+) variant, but that's your choice.

**Comment by notriddle** [comment]
I'll add a copy of the licenses themselves, but a full-text license header in the files shouldn't be necessary.

**Comment by notriddle** [comment]
See also: https://github.com/rust-lang/rust/issues/9070#issuecomment-31860335
