### ISSUE TITLE
Invite the bot into all applicable organizations

### ISSUE THREAD

**Issue by notriddle** [AelitaBot/aelita#79]
To actually see the list of teams, the bot needs to be a member of the org (or even the team, if it's secret, but I'm not sure how much we care about that case). Signup should do that automatically.

CC georust/rust-wkt#30

**Comment by frewsxcv** [comment]
>the bot needs to be a member of a team

They actually just need to be a "Member" of the organization, not necessarily in a team.

**Comment by notriddle** [comment]
Edited.
