### ISSUE TITLE
Panic on startup with `Pipeline went away: RecvError`.

### ISSUE THREAD

**Issue by cristicbz** [AelitaBot/aelita#94]
Running

```
cargo build
RUST_LOG=debug RUST_BACKTRACE=1 target/debug/aelita config.toml
```

panics with

<details>
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Dangling', ../src/libcore/result.rs:788
stack backtrace:
thread 'thread '<unnamed>' panicked at '<unnamed>Pipeline went away: RecvError' panicked at '', Pipeline went away: RecvError../src/libcore/result.rs', :../src/libcore/result.rs788:
788
   1:     0x55a151468503 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x55a15146f17c - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x55a15146dece - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x55a15146e5e8 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     0x55a15146e482 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:     0x55a15146e3b0 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:     0x55a15146e331 - rust_begin_unwind
   8:     0x55a15147bbcf - core::panicking::panic_fmt::hc5789f4e80194729
   9:     0x55a150dd80d2 - core::result::unwrap_failed::h31bfe3e2101c2036
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:29
  10:     0x55a150d7d5b1 - _<core..result..Result<T, E>>::unwrap::hce55eed0e3e9b9e8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:726
  11:     0x55a1510d2ae3 - aelita::main::h3044416cb8f773c3
                        at /home/ccc/g/aelita/src/main.rs:65
  12:     0x55a151476c66 - __rust_maybe_catch_panic
  13:     0x55a15146d632 - std::rt::lang_start::h352a66f5026f54bd
  14:     0x55a151110f33 - main
  15:     0x7fdff988cf44 - __libc_start_main
  16:     0x55a150cce758 - <unknown>
  17:                0x0 - <unknown>
stack backtrace:
   1:     0x55a151468503 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x55a15146f17c - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x55a15146dece - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x55a15146e5e8 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     % 
```
</details>

My `config.toml` is the travis example one, just with my organisation, tokens and users filled in. I left the `listen` endpoints to the `localhost` ones, since I wanted to try it out locally first (I understand that I won't get any notifications from Github if I'm listening on `localhost`, but I expected it to start running anyway).

Sorry if I missed some critical step, please help! Once I manage to get it all set up, I wanted to write a little getting started blog post.

Thanks!

**Comment by notriddle** [comment]
The config examples have fallen a bit out-of-date. Underneath the github.status part, add another section (with no options in it) called `[github.git]`. This tells it to use Github's API for VCS work, instead of the bare Git binary. You also haven't configured the Git binary, of course, which is what gives it the "dangling error" (no VCS worker configured).

The error messages are in serious need of actually being written, as well. I've been trying to spend most of my time on error handling while the program is actually running, though.

**Comment by notriddle** [comment]
Also, support questions should probably be leveled on Gitter, instead of the issue tracker. The problem with terrible error messages has been logged as #95. Thanks!

**Comment by cristicbz** [comment]
Fair enough sorry for noise and thanks for the help (and for writing this)!

(there's probably another issue to file about the example toml files being out of date, but I won't open it to leave it up to you and not create any more noise)

**Comment by notriddle** [comment]
No problem, go ahead and file issues!
